apiVersion: v1
kind: Secret
metadata:
  name: lanyard-secret
  namespace: lanyard
type: Opaque
stringData:
  DATABASE_URL: "postgres://lanyard:CHANGE_ME@postgres:5432/lanyard"
  BETTER_AUTH_SECRET: "CHANGE_ME_TO_256_BIT_SECRET"
  SMTP_HOST: ""
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_PASS: ""
  SMTP_FROM: "noreply@example.com"
  RESEND_API_KEY: ""
  REDIS_URL: ""
