/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as ApiUserSessionsRouteImport } from './routes/api/user/sessions'
import { Route as ApiUserSecurityStatusRouteImport } from './routes/api/user/security-status'
import { Route as ApiUserProfileRouteImport } from './routes/api/user/profile'
import { Route as ApiUserPasswordRouteImport } from './routes/api/user/password'
import { Route as ApiUserOrganizationsRouteImport } from './routes/api/user/organizations'
import { Route as ApiUserConnectedAppsRouteImport } from './routes/api/user/connected-apps'
import { Route as ApiServicesRegisterRouteImport } from './routes/api/services/register'
import { Route as ApiServicesHeartbeatRouteImport } from './routes/api/services/heartbeat'
import { Route as ApiServicesCatalogRouteImport } from './routes/api/services/catalog'
import { Route as ApiServicesServiceIdRouteImport } from './routes/api/services/$serviceId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAdminClientsRouteImport } from './routes/api/admin/clients'
import { Route as ApiAdminBrandingRouteImport } from './routes/api/admin/branding'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api/admin/users/$userId'
import { Route as ApiAdminClientsClientIdRouteImport } from './routes/api/admin/clients/$clientId'
import { Route as ApiUserSessionsSessionIdRevokeRouteImport } from './routes/api/user/sessions/$sessionId/revoke'
import { Route as ApiUserConnectedAppsConsentIdRevokeRouteImport } from './routes/api/user/connected-apps/$consentId/revoke'
import { Route as ApiAdminUsersUserIdVerifyEmailRouteImport } from './routes/api/admin/users/$userId/verify-email'
import { Route as ApiAdminUsersUserIdUnbanRouteImport } from './routes/api/admin/users/$userId/unban'
import { Route as ApiAdminUsersUserIdSetRoleRouteImport } from './routes/api/admin/users/$userId/set-role'
import { Route as ApiAdminUsersUserIdBanRouteImport } from './routes/api/admin/users/$userId/ban'
import { Route as ApiAdminUsersUserIdActionsRouteImport } from './routes/api/admin/users/$userId/actions'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const ApiUserSessionsRoute = ApiUserSessionsRouteImport.update({
  id: '/api/user/sessions',
  path: '/api/user/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSecurityStatusRoute = ApiUserSecurityStatusRouteImport.update({
  id: '/api/user/security-status',
  path: '/api/user/security-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user/profile',
  path: '/api/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPasswordRoute = ApiUserPasswordRouteImport.update({
  id: '/api/user/password',
  path: '/api/user/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserOrganizationsRoute = ApiUserOrganizationsRouteImport.update({
  id: '/api/user/organizations',
  path: '/api/user/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserConnectedAppsRoute = ApiUserConnectedAppsRouteImport.update({
  id: '/api/user/connected-apps',
  path: '/api/user/connected-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesRegisterRoute = ApiServicesRegisterRouteImport.update({
  id: '/api/services/register',
  path: '/api/services/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesHeartbeatRoute = ApiServicesHeartbeatRouteImport.update({
  id: '/api/services/heartbeat',
  path: '/api/services/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesCatalogRoute = ApiServicesCatalogRouteImport.update({
  id: '/api/services/catalog',
  path: '/api/services/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesServiceIdRoute = ApiServicesServiceIdRouteImport.update({
  id: '/api/services/$serviceId',
  path: '/api/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminClientsRoute = ApiAdminClientsRouteImport.update({
  id: '/api/admin/clients',
  path: '/api/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBrandingRoute = ApiAdminBrandingRouteImport.update({
  id: '/api/admin/branding',
  path: '/api/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiAdminClientsClientIdRoute = ApiAdminClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ApiAdminClientsRoute,
} as any)
const ApiUserSessionsSessionIdRevokeRoute =
  ApiUserSessionsSessionIdRevokeRouteImport.update({
    id: '/$sessionId/revoke',
    path: '/$sessionId/revoke',
    getParentRoute: () => ApiUserSessionsRoute,
  } as any)
const ApiUserConnectedAppsConsentIdRevokeRoute =
  ApiUserConnectedAppsConsentIdRevokeRouteImport.update({
    id: '/$consentId/revoke',
    path: '/$consentId/revoke',
    getParentRoute: () => ApiUserConnectedAppsRoute,
  } as any)
const ApiAdminUsersUserIdVerifyEmailRoute =
  ApiAdminUsersUserIdVerifyEmailRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)
const ApiAdminUsersUserIdUnbanRoute =
  ApiAdminUsersUserIdUnbanRouteImport.update({
    id: '/unban',
    path: '/unban',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)
const ApiAdminUsersUserIdSetRoleRoute =
  ApiAdminUsersUserIdSetRoleRouteImport.update({
    id: '/set-role',
    path: '/set-role',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)
const ApiAdminUsersUserIdBanRoute = ApiAdminUsersUserIdBanRouteImport.update({
  id: '/ban',
  path: '/ban',
  getParentRoute: () => ApiAdminUsersUserIdRoute,
} as any)
const ApiAdminUsersUserIdActionsRoute =
  ApiAdminUsersUserIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/api/health': typeof ApiHealthRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/api/admin/branding': typeof ApiAdminBrandingRoute
  '/api/admin/clients': typeof ApiAdminClientsRouteWithChildren
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/services/$serviceId': typeof ApiServicesServiceIdRoute
  '/api/services/catalog': typeof ApiServicesCatalogRoute
  '/api/services/heartbeat': typeof ApiServicesHeartbeatRoute
  '/api/services/register': typeof ApiServicesRegisterRoute
  '/api/user/connected-apps': typeof ApiUserConnectedAppsRouteWithChildren
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/api/user/password': typeof ApiUserPasswordRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/security-status': typeof ApiUserSecurityStatusRoute
  '/api/user/sessions': typeof ApiUserSessionsRouteWithChildren
  '/api/admin/clients/$clientId': typeof ApiAdminClientsClientIdRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRouteWithChildren
  '/api/admin/users/$userId/actions': typeof ApiAdminUsersUserIdActionsRoute
  '/api/admin/users/$userId/ban': typeof ApiAdminUsersUserIdBanRoute
  '/api/admin/users/$userId/set-role': typeof ApiAdminUsersUserIdSetRoleRoute
  '/api/admin/users/$userId/unban': typeof ApiAdminUsersUserIdUnbanRoute
  '/api/admin/users/$userId/verify-email': typeof ApiAdminUsersUserIdVerifyEmailRoute
  '/api/user/connected-apps/$consentId/revoke': typeof ApiUserConnectedAppsConsentIdRevokeRoute
  '/api/user/sessions/$sessionId/revoke': typeof ApiUserSessionsSessionIdRevokeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/api/health': typeof ApiHealthRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/api/admin/branding': typeof ApiAdminBrandingRoute
  '/api/admin/clients': typeof ApiAdminClientsRouteWithChildren
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/services/$serviceId': typeof ApiServicesServiceIdRoute
  '/api/services/catalog': typeof ApiServicesCatalogRoute
  '/api/services/heartbeat': typeof ApiServicesHeartbeatRoute
  '/api/services/register': typeof ApiServicesRegisterRoute
  '/api/user/connected-apps': typeof ApiUserConnectedAppsRouteWithChildren
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/api/user/password': typeof ApiUserPasswordRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/security-status': typeof ApiUserSecurityStatusRoute
  '/api/user/sessions': typeof ApiUserSessionsRouteWithChildren
  '/api/admin/clients/$clientId': typeof ApiAdminClientsClientIdRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRouteWithChildren
  '/api/admin/users/$userId/actions': typeof ApiAdminUsersUserIdActionsRoute
  '/api/admin/users/$userId/ban': typeof ApiAdminUsersUserIdBanRoute
  '/api/admin/users/$userId/set-role': typeof ApiAdminUsersUserIdSetRoleRoute
  '/api/admin/users/$userId/unban': typeof ApiAdminUsersUserIdUnbanRoute
  '/api/admin/users/$userId/verify-email': typeof ApiAdminUsersUserIdVerifyEmailRoute
  '/api/user/connected-apps/$consentId/revoke': typeof ApiUserConnectedAppsConsentIdRevokeRoute
  '/api/user/sessions/$sessionId/revoke': typeof ApiUserSessionsSessionIdRevokeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/api/health': typeof ApiHealthRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/api/admin/branding': typeof ApiAdminBrandingRoute
  '/api/admin/clients': typeof ApiAdminClientsRouteWithChildren
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/services/$serviceId': typeof ApiServicesServiceIdRoute
  '/api/services/catalog': typeof ApiServicesCatalogRoute
  '/api/services/heartbeat': typeof ApiServicesHeartbeatRoute
  '/api/services/register': typeof ApiServicesRegisterRoute
  '/api/user/connected-apps': typeof ApiUserConnectedAppsRouteWithChildren
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/api/user/password': typeof ApiUserPasswordRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/security-status': typeof ApiUserSecurityStatusRoute
  '/api/user/sessions': typeof ApiUserSessionsRouteWithChildren
  '/api/admin/clients/$clientId': typeof ApiAdminClientsClientIdRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRouteWithChildren
  '/api/admin/users/$userId/actions': typeof ApiAdminUsersUserIdActionsRoute
  '/api/admin/users/$userId/ban': typeof ApiAdminUsersUserIdBanRoute
  '/api/admin/users/$userId/set-role': typeof ApiAdminUsersUserIdSetRoleRoute
  '/api/admin/users/$userId/unban': typeof ApiAdminUsersUserIdUnbanRoute
  '/api/admin/users/$userId/verify-email': typeof ApiAdminUsersUserIdVerifyEmailRoute
  '/api/user/connected-apps/$consentId/revoke': typeof ApiUserConnectedAppsConsentIdRevokeRoute
  '/api/user/sessions/$sessionId/revoke': typeof ApiUserSessionsSessionIdRevokeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/health'
    | '/oauth/consent'
    | '/api/admin/branding'
    | '/api/admin/clients'
    | '/api/admin/settings'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/services/$serviceId'
    | '/api/services/catalog'
    | '/api/services/heartbeat'
    | '/api/services/register'
    | '/api/user/connected-apps'
    | '/api/user/organizations'
    | '/api/user/password'
    | '/api/user/profile'
    | '/api/user/security-status'
    | '/api/user/sessions'
    | '/api/admin/clients/$clientId'
    | '/api/admin/users/$userId'
    | '/api/admin/users/$userId/actions'
    | '/api/admin/users/$userId/ban'
    | '/api/admin/users/$userId/set-role'
    | '/api/admin/users/$userId/unban'
    | '/api/admin/users/$userId/verify-email'
    | '/api/user/connected-apps/$consentId/revoke'
    | '/api/user/sessions/$sessionId/revoke'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/health'
    | '/oauth/consent'
    | '/api/admin/branding'
    | '/api/admin/clients'
    | '/api/admin/settings'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/services/$serviceId'
    | '/api/services/catalog'
    | '/api/services/heartbeat'
    | '/api/services/register'
    | '/api/user/connected-apps'
    | '/api/user/organizations'
    | '/api/user/password'
    | '/api/user/profile'
    | '/api/user/security-status'
    | '/api/user/sessions'
    | '/api/admin/clients/$clientId'
    | '/api/admin/users/$userId'
    | '/api/admin/users/$userId/actions'
    | '/api/admin/users/$userId/ban'
    | '/api/admin/users/$userId/set-role'
    | '/api/admin/users/$userId/unban'
    | '/api/admin/users/$userId/verify-email'
    | '/api/user/connected-apps/$consentId/revoke'
    | '/api/user/sessions/$sessionId/revoke'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/register'
    | '/_public/reset-password'
    | '/api/health'
    | '/oauth/consent'
    | '/api/admin/branding'
    | '/api/admin/clients'
    | '/api/admin/settings'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/services/$serviceId'
    | '/api/services/catalog'
    | '/api/services/heartbeat'
    | '/api/services/register'
    | '/api/user/connected-apps'
    | '/api/user/organizations'
    | '/api/user/password'
    | '/api/user/profile'
    | '/api/user/security-status'
    | '/api/user/sessions'
    | '/api/admin/clients/$clientId'
    | '/api/admin/users/$userId'
    | '/api/admin/users/$userId/actions'
    | '/api/admin/users/$userId/ban'
    | '/api/admin/users/$userId/set-role'
    | '/api/admin/users/$userId/unban'
    | '/api/admin/users/$userId/verify-email'
    | '/api/user/connected-apps/$consentId/revoke'
    | '/api/user/sessions/$sessionId/revoke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAdminBrandingRoute: typeof ApiAdminBrandingRoute
  ApiAdminClientsRoute: typeof ApiAdminClientsRouteWithChildren
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiServicesServiceIdRoute: typeof ApiServicesServiceIdRoute
  ApiServicesCatalogRoute: typeof ApiServicesCatalogRoute
  ApiServicesHeartbeatRoute: typeof ApiServicesHeartbeatRoute
  ApiServicesRegisterRoute: typeof ApiServicesRegisterRoute
  ApiUserConnectedAppsRoute: typeof ApiUserConnectedAppsRouteWithChildren
  ApiUserOrganizationsRoute: typeof ApiUserOrganizationsRoute
  ApiUserPasswordRoute: typeof ApiUserPasswordRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ApiUserSecurityStatusRoute: typeof ApiUserSecurityStatusRoute
  ApiUserSessionsRoute: typeof ApiUserSessionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/user/sessions': {
      id: '/api/user/sessions'
      path: '/api/user/sessions'
      fullPath: '/api/user/sessions'
      preLoaderRoute: typeof ApiUserSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/security-status': {
      id: '/api/user/security-status'
      path: '/api/user/security-status'
      fullPath: '/api/user/security-status'
      preLoaderRoute: typeof ApiUserSecurityStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile': {
      id: '/api/user/profile'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/password': {
      id: '/api/user/password'
      path: '/api/user/password'
      fullPath: '/api/user/password'
      preLoaderRoute: typeof ApiUserPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/organizations': {
      id: '/api/user/organizations'
      path: '/api/user/organizations'
      fullPath: '/api/user/organizations'
      preLoaderRoute: typeof ApiUserOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/connected-apps': {
      id: '/api/user/connected-apps'
      path: '/api/user/connected-apps'
      fullPath: '/api/user/connected-apps'
      preLoaderRoute: typeof ApiUserConnectedAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/register': {
      id: '/api/services/register'
      path: '/api/services/register'
      fullPath: '/api/services/register'
      preLoaderRoute: typeof ApiServicesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/heartbeat': {
      id: '/api/services/heartbeat'
      path: '/api/services/heartbeat'
      fullPath: '/api/services/heartbeat'
      preLoaderRoute: typeof ApiServicesHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/catalog': {
      id: '/api/services/catalog'
      path: '/api/services/catalog'
      fullPath: '/api/services/catalog'
      preLoaderRoute: typeof ApiServicesCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/$serviceId': {
      id: '/api/services/$serviceId'
      path: '/api/services/$serviceId'
      fullPath: '/api/services/$serviceId'
      preLoaderRoute: typeof ApiServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/clients': {
      id: '/api/admin/clients'
      path: '/api/admin/clients'
      fullPath: '/api/admin/clients'
      preLoaderRoute: typeof ApiAdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/branding': {
      id: '/api/admin/branding'
      path: '/api/admin/branding'
      fullPath: '/api/admin/branding'
      preLoaderRoute: typeof ApiAdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/clients/$clientId': {
      id: '/api/admin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/api/admin/clients/$clientId'
      preLoaderRoute: typeof ApiAdminClientsClientIdRouteImport
      parentRoute: typeof ApiAdminClientsRoute
    }
    '/api/user/sessions/$sessionId/revoke': {
      id: '/api/user/sessions/$sessionId/revoke'
      path: '/$sessionId/revoke'
      fullPath: '/api/user/sessions/$sessionId/revoke'
      preLoaderRoute: typeof ApiUserSessionsSessionIdRevokeRouteImport
      parentRoute: typeof ApiUserSessionsRoute
    }
    '/api/user/connected-apps/$consentId/revoke': {
      id: '/api/user/connected-apps/$consentId/revoke'
      path: '/$consentId/revoke'
      fullPath: '/api/user/connected-apps/$consentId/revoke'
      preLoaderRoute: typeof ApiUserConnectedAppsConsentIdRevokeRouteImport
      parentRoute: typeof ApiUserConnectedAppsRoute
    }
    '/api/admin/users/$userId/verify-email': {
      id: '/api/admin/users/$userId/verify-email'
      path: '/verify-email'
      fullPath: '/api/admin/users/$userId/verify-email'
      preLoaderRoute: typeof ApiAdminUsersUserIdVerifyEmailRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/users/$userId/unban': {
      id: '/api/admin/users/$userId/unban'
      path: '/unban'
      fullPath: '/api/admin/users/$userId/unban'
      preLoaderRoute: typeof ApiAdminUsersUserIdUnbanRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/users/$userId/set-role': {
      id: '/api/admin/users/$userId/set-role'
      path: '/set-role'
      fullPath: '/api/admin/users/$userId/set-role'
      preLoaderRoute: typeof ApiAdminUsersUserIdSetRoleRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/users/$userId/ban': {
      id: '/api/admin/users/$userId/ban'
      path: '/ban'
      fullPath: '/api/admin/users/$userId/ban'
      preLoaderRoute: typeof ApiAdminUsersUserIdBanRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/users/$userId/actions': {
      id: '/api/admin/users/$userId/actions'
      path: '/actions'
      fullPath: '/api/admin/users/$userId/actions'
      preLoaderRoute: typeof ApiAdminUsersUserIdActionsRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
  }
}

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface ApiAdminClientsRouteChildren {
  ApiAdminClientsClientIdRoute: typeof ApiAdminClientsClientIdRoute
}

const ApiAdminClientsRouteChildren: ApiAdminClientsRouteChildren = {
  ApiAdminClientsClientIdRoute: ApiAdminClientsClientIdRoute,
}

const ApiAdminClientsRouteWithChildren = ApiAdminClientsRoute._addFileChildren(
  ApiAdminClientsRouteChildren,
)

interface ApiAdminUsersUserIdRouteChildren {
  ApiAdminUsersUserIdActionsRoute: typeof ApiAdminUsersUserIdActionsRoute
  ApiAdminUsersUserIdBanRoute: typeof ApiAdminUsersUserIdBanRoute
  ApiAdminUsersUserIdSetRoleRoute: typeof ApiAdminUsersUserIdSetRoleRoute
  ApiAdminUsersUserIdUnbanRoute: typeof ApiAdminUsersUserIdUnbanRoute
  ApiAdminUsersUserIdVerifyEmailRoute: typeof ApiAdminUsersUserIdVerifyEmailRoute
}

const ApiAdminUsersUserIdRouteChildren: ApiAdminUsersUserIdRouteChildren = {
  ApiAdminUsersUserIdActionsRoute: ApiAdminUsersUserIdActionsRoute,
  ApiAdminUsersUserIdBanRoute: ApiAdminUsersUserIdBanRoute,
  ApiAdminUsersUserIdSetRoleRoute: ApiAdminUsersUserIdSetRoleRoute,
  ApiAdminUsersUserIdUnbanRoute: ApiAdminUsersUserIdUnbanRoute,
  ApiAdminUsersUserIdVerifyEmailRoute: ApiAdminUsersUserIdVerifyEmailRoute,
}

const ApiAdminUsersUserIdRouteWithChildren =
  ApiAdminUsersUserIdRoute._addFileChildren(ApiAdminUsersUserIdRouteChildren)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRouteWithChildren
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRouteWithChildren,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiUserConnectedAppsRouteChildren {
  ApiUserConnectedAppsConsentIdRevokeRoute: typeof ApiUserConnectedAppsConsentIdRevokeRoute
}

const ApiUserConnectedAppsRouteChildren: ApiUserConnectedAppsRouteChildren = {
  ApiUserConnectedAppsConsentIdRevokeRoute:
    ApiUserConnectedAppsConsentIdRevokeRoute,
}

const ApiUserConnectedAppsRouteWithChildren =
  ApiUserConnectedAppsRoute._addFileChildren(ApiUserConnectedAppsRouteChildren)

interface ApiUserSessionsRouteChildren {
  ApiUserSessionsSessionIdRevokeRoute: typeof ApiUserSessionsSessionIdRevokeRoute
}

const ApiUserSessionsRouteChildren: ApiUserSessionsRouteChildren = {
  ApiUserSessionsSessionIdRevokeRoute: ApiUserSessionsSessionIdRevokeRoute,
}

const ApiUserSessionsRouteWithChildren = ApiUserSessionsRoute._addFileChildren(
  ApiUserSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAdminBrandingRoute: ApiAdminBrandingRoute,
  ApiAdminClientsRoute: ApiAdminClientsRouteWithChildren,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiServicesServiceIdRoute: ApiServicesServiceIdRoute,
  ApiServicesCatalogRoute: ApiServicesCatalogRoute,
  ApiServicesHeartbeatRoute: ApiServicesHeartbeatRoute,
  ApiServicesRegisterRoute: ApiServicesRegisterRoute,
  ApiUserConnectedAppsRoute: ApiUserConnectedAppsRouteWithChildren,
  ApiUserOrganizationsRoute: ApiUserOrganizationsRoute,
  ApiUserPasswordRoute: ApiUserPasswordRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiUserSecurityStatusRoute: ApiUserSecurityStatusRoute,
  ApiUserSessionsRoute: ApiUserSessionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
