/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as ApiUserSessionsRouteImport } from './routes/api/user/sessions'
import { Route as ApiUserSecurityStatusRouteImport } from './routes/api/user/security-status'
import { Route as ApiUserProfileRouteImport } from './routes/api/user/profile'
import { Route as ApiUserPasswordRouteImport } from './routes/api/user/password'
import { Route as ApiUserPasskeysRouteImport } from './routes/api/user/passkeys'
import { Route as ApiUserOrganizationsRouteImport } from './routes/api/user/organizations'
import { Route as ApiUserDepartmentsRouteImport } from './routes/api/user/departments'
import { Route as ApiUserConnectedAppsRouteImport } from './routes/api/user/connected-apps'
import { Route as ApiUploadAvatarRouteImport } from './routes/api/upload/avatar'
import { Route as ApiServicesRegisterRouteImport } from './routes/api/services/register'
import { Route as ApiServicesHeartbeatRouteImport } from './routes/api/services/heartbeat'
import { Route as ApiServicesCatalogRouteImport } from './routes/api/services/catalog'
import { Route as ApiServicesServiceIdRouteImport } from './routes/api/services/$serviceId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAdminServicesRouteImport } from './routes/api/admin/services'
import { Route as ApiAdminDepartmentsRouteImport } from './routes/api/admin/departments'
import { Route as ApiAdminClientsRouteImport } from './routes/api/admin/clients'
import { Route as ApiAdminBrandingRouteImport } from './routes/api/admin/branding'
import { Route as ApiUser2faStatusRouteImport } from './routes/api/user/2fa/status'
import { Route as ApiAdminUsersCreateRouteImport } from './routes/api/admin/users/create'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api/admin/users/$userId'
import { Route as ApiAdminServicesServiceIdRouteImport } from './routes/api/admin/services/$serviceId'
import { Route as ApiAdminDepartmentsCreateRouteImport } from './routes/api/admin/departments/create'
import { Route as ApiAdminDepartmentsDepartmentIdRouteImport } from './routes/api/admin/departments/$departmentId'
import { Route as ApiAdminClientsRegisterRouteImport } from './routes/api/admin/clients/register'
import { Route as ApiAdminClientsClientIdRouteImport } from './routes/api/admin/clients/$clientId'
import { Route as ApiUserSessionsSessionIdRevokeRouteImport } from './routes/api/user/sessions/$sessionId/revoke'
import { Route as ApiUserPasskeysPasskeyIdDeleteRouteImport } from './routes/api/user/passkeys/$passkeyId/delete'
import { Route as ApiUserConnectedAppsConsentIdRevokeRouteImport } from './routes/api/user/connected-apps/$consentId/revoke'
import { Route as ApiAdminUsersUserIdVerifyEmailRouteImport } from './routes/api/admin/users/$userId/verify-email'
import { Route as ApiAdminUsersUserIdUnbanRouteImport } from './routes/api/admin/users/$userId/unban'
import { Route as ApiAdminUsersUserIdSetRoleRouteImport } from './routes/api/admin/users/$userId/set-role'
import { Route as ApiAdminUsersUserIdBanRouteImport } from './routes/api/admin/users/$userId/ban'
import { Route as ApiAdminUsersUserIdActionsRouteImport } from './routes/api/admin/users/$userId/actions'
import { Route as ApiAdminServicesServiceIdToggleRouteImport } from './routes/api/admin/services/$serviceId/toggle'
import { Route as ApiAdminServicesServiceIdDeleteRouteImport } from './routes/api/admin/services/$serviceId/delete'
import { Route as ApiAdminServicesServiceIdActionsRouteImport } from './routes/api/admin/services/$serviceId/actions'
import { Route as ApiAdminDepartmentsDepartmentIdTeamsRouteImport } from './routes/api/admin/departments/$departmentId/teams'
import { Route as ApiAdminDepartmentsDepartmentIdMembersRouteImport } from './routes/api/admin/departments/$departmentId/members'
import { Route as ApiAdminDepartmentsDepartmentIdDeleteRouteImport } from './routes/api/admin/departments/$departmentId/delete'
import { Route as ApiAdminDepartmentsDepartmentIdActionsRouteImport } from './routes/api/admin/departments/$departmentId/actions'
import { Route as ApiAdminClientsClientIdActionsRouteImport } from './routes/api/admin/clients/$clientId/actions'
import { Route as ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteImport } from './routes/api/admin/departments/$departmentId/teams/$teamId/members'
import { Route as ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRouteImport } from './routes/api/admin/departments/$departmentId/teams/$teamId/delete'
import { Route as ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRouteImport } from './routes/api/admin/departments/$departmentId/members/$memberId/role'
import { Route as ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRouteImport } from './routes/api/admin/departments/$departmentId/members/$memberId/remove'
import { Route as ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRouteImport } from './routes/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const ApiUserSessionsRoute = ApiUserSessionsRouteImport.update({
  id: '/api/user/sessions',
  path: '/api/user/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSecurityStatusRoute = ApiUserSecurityStatusRouteImport.update({
  id: '/api/user/security-status',
  path: '/api/user/security-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user/profile',
  path: '/api/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPasswordRoute = ApiUserPasswordRouteImport.update({
  id: '/api/user/password',
  path: '/api/user/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPasskeysRoute = ApiUserPasskeysRouteImport.update({
  id: '/api/user/passkeys',
  path: '/api/user/passkeys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserOrganizationsRoute = ApiUserOrganizationsRouteImport.update({
  id: '/api/user/organizations',
  path: '/api/user/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserDepartmentsRoute = ApiUserDepartmentsRouteImport.update({
  id: '/api/user/departments',
  path: '/api/user/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserConnectedAppsRoute = ApiUserConnectedAppsRouteImport.update({
  id: '/api/user/connected-apps',
  path: '/api/user/connected-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadAvatarRoute = ApiUploadAvatarRouteImport.update({
  id: '/api/upload/avatar',
  path: '/api/upload/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesRegisterRoute = ApiServicesRegisterRouteImport.update({
  id: '/api/services/register',
  path: '/api/services/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesHeartbeatRoute = ApiServicesHeartbeatRouteImport.update({
  id: '/api/services/heartbeat',
  path: '/api/services/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesCatalogRoute = ApiServicesCatalogRouteImport.update({
  id: '/api/services/catalog',
  path: '/api/services/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesServiceIdRoute = ApiServicesServiceIdRouteImport.update({
  id: '/api/services/$serviceId',
  path: '/api/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminServicesRoute = ApiAdminServicesRouteImport.update({
  id: '/api/admin/services',
  path: '/api/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDepartmentsRoute = ApiAdminDepartmentsRouteImport.update({
  id: '/api/admin/departments',
  path: '/api/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminClientsRoute = ApiAdminClientsRouteImport.update({
  id: '/api/admin/clients',
  path: '/api/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBrandingRoute = ApiAdminBrandingRouteImport.update({
  id: '/api/admin/branding',
  path: '/api/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUser2faStatusRoute = ApiUser2faStatusRouteImport.update({
  id: '/api/user/2fa/status',
  path: '/api/user/2fa/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersCreateRoute = ApiAdminUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiAdminServicesServiceIdRoute =
  ApiAdminServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => ApiAdminServicesRoute,
  } as any)
const ApiAdminDepartmentsCreateRoute =
  ApiAdminDepartmentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => ApiAdminDepartmentsRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdRoute =
  ApiAdminDepartmentsDepartmentIdRouteImport.update({
    id: '/$departmentId',
    path: '/$departmentId',
    getParentRoute: () => ApiAdminDepartmentsRoute,
  } as any)
const ApiAdminClientsRegisterRoute = ApiAdminClientsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ApiAdminClientsRoute,
} as any)
const ApiAdminClientsClientIdRoute = ApiAdminClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ApiAdminClientsRoute,
} as any)
const ApiUserSessionsSessionIdRevokeRoute =
  ApiUserSessionsSessionIdRevokeRouteImport.update({
    id: '/$sessionId/revoke',
    path: '/$sessionId/revoke',
    getParentRoute: () => ApiUserSessionsRoute,
  } as any)
const ApiUserPasskeysPasskeyIdDeleteRoute =
  ApiUserPasskeysPasskeyIdDeleteRouteImport.update({
    id: '/$passkeyId/delete',
    path: '/$passkeyId/delete',
    getParentRoute: () => ApiUserPasskeysRoute,
  } as any)
const ApiUserConnectedAppsConsentIdRevokeRoute =
  ApiUserConnectedAppsConsentIdRevokeRouteImport.update({
    id: '/$consentId/revoke',
    path: '/$consentId/revoke',
    getParentRoute: () => ApiUserConnectedAppsRoute,
  } as any)
const ApiAdminUsersUserIdVerifyEmailRoute =
  ApiAdminUsersUserIdVerifyEmailRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)
const ApiAdminUsersUserIdUnbanRoute =
  ApiAdminUsersUserIdUnbanRouteImport.update({
    id: '/unban',
    path: '/unban',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)
const ApiAdminUsersUserIdSetRoleRoute =
  ApiAdminUsersUserIdSetRoleRouteImport.update({
    id: '/set-role',
    path: '/set-role',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)
const ApiAdminUsersUserIdBanRoute = ApiAdminUsersUserIdBanRouteImport.update({
  id: '/ban',
  path: '/ban',
  getParentRoute: () => ApiAdminUsersUserIdRoute,
} as any)
const ApiAdminUsersUserIdActionsRoute =
  ApiAdminUsersUserIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)
const ApiAdminServicesServiceIdToggleRoute =
  ApiAdminServicesServiceIdToggleRouteImport.update({
    id: '/toggle',
    path: '/toggle',
    getParentRoute: () => ApiAdminServicesServiceIdRoute,
  } as any)
const ApiAdminServicesServiceIdDeleteRoute =
  ApiAdminServicesServiceIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => ApiAdminServicesServiceIdRoute,
  } as any)
const ApiAdminServicesServiceIdActionsRoute =
  ApiAdminServicesServiceIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ApiAdminServicesServiceIdRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdTeamsRoute =
  ApiAdminDepartmentsDepartmentIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => ApiAdminDepartmentsDepartmentIdRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdMembersRoute =
  ApiAdminDepartmentsDepartmentIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ApiAdminDepartmentsDepartmentIdRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdDeleteRoute =
  ApiAdminDepartmentsDepartmentIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => ApiAdminDepartmentsDepartmentIdRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdActionsRoute =
  ApiAdminDepartmentsDepartmentIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ApiAdminDepartmentsDepartmentIdRoute,
  } as any)
const ApiAdminClientsClientIdActionsRoute =
  ApiAdminClientsClientIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ApiAdminClientsClientIdRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRoute =
  ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteImport.update({
    id: '/$teamId/members',
    path: '/$teamId/members',
    getParentRoute: () => ApiAdminDepartmentsDepartmentIdTeamsRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRoute =
  ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRouteImport.update({
    id: '/$teamId/delete',
    path: '/$teamId/delete',
    getParentRoute: () => ApiAdminDepartmentsDepartmentIdTeamsRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRoute =
  ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRouteImport.update({
    id: '/$memberId/role',
    path: '/$memberId/role',
    getParentRoute: () => ApiAdminDepartmentsDepartmentIdMembersRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRoute =
  ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRouteImport.update({
    id: '/$memberId/remove',
    path: '/$memberId/remove',
    getParentRoute: () => ApiAdminDepartmentsDepartmentIdMembersRoute,
  } as any)
const ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRoute =
  ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRouteImport.update(
    {
      id: '/$teamMemberId/remove',
      path: '/$teamMemberId/remove',
      getParentRoute: () =>
        ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/api/health': typeof ApiHealthRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/api/admin/branding': typeof ApiAdminBrandingRoute
  '/api/admin/clients': typeof ApiAdminClientsRouteWithChildren
  '/api/admin/departments': typeof ApiAdminDepartmentsRouteWithChildren
  '/api/admin/services': typeof ApiAdminServicesRouteWithChildren
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/services/$serviceId': typeof ApiServicesServiceIdRoute
  '/api/services/catalog': typeof ApiServicesCatalogRoute
  '/api/services/heartbeat': typeof ApiServicesHeartbeatRoute
  '/api/services/register': typeof ApiServicesRegisterRoute
  '/api/upload/avatar': typeof ApiUploadAvatarRoute
  '/api/user/connected-apps': typeof ApiUserConnectedAppsRouteWithChildren
  '/api/user/departments': typeof ApiUserDepartmentsRoute
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/api/user/passkeys': typeof ApiUserPasskeysRouteWithChildren
  '/api/user/password': typeof ApiUserPasswordRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/security-status': typeof ApiUserSecurityStatusRoute
  '/api/user/sessions': typeof ApiUserSessionsRouteWithChildren
  '/api/admin/clients/$clientId': typeof ApiAdminClientsClientIdRouteWithChildren
  '/api/admin/clients/register': typeof ApiAdminClientsRegisterRoute
  '/api/admin/departments/$departmentId': typeof ApiAdminDepartmentsDepartmentIdRouteWithChildren
  '/api/admin/departments/create': typeof ApiAdminDepartmentsCreateRoute
  '/api/admin/services/$serviceId': typeof ApiAdminServicesServiceIdRouteWithChildren
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRouteWithChildren
  '/api/admin/users/create': typeof ApiAdminUsersCreateRoute
  '/api/user/2fa/status': typeof ApiUser2faStatusRoute
  '/api/admin/clients/$clientId/actions': typeof ApiAdminClientsClientIdActionsRoute
  '/api/admin/departments/$departmentId/actions': typeof ApiAdminDepartmentsDepartmentIdActionsRoute
  '/api/admin/departments/$departmentId/delete': typeof ApiAdminDepartmentsDepartmentIdDeleteRoute
  '/api/admin/departments/$departmentId/members': typeof ApiAdminDepartmentsDepartmentIdMembersRouteWithChildren
  '/api/admin/departments/$departmentId/teams': typeof ApiAdminDepartmentsDepartmentIdTeamsRouteWithChildren
  '/api/admin/services/$serviceId/actions': typeof ApiAdminServicesServiceIdActionsRoute
  '/api/admin/services/$serviceId/delete': typeof ApiAdminServicesServiceIdDeleteRoute
  '/api/admin/services/$serviceId/toggle': typeof ApiAdminServicesServiceIdToggleRoute
  '/api/admin/users/$userId/actions': typeof ApiAdminUsersUserIdActionsRoute
  '/api/admin/users/$userId/ban': typeof ApiAdminUsersUserIdBanRoute
  '/api/admin/users/$userId/set-role': typeof ApiAdminUsersUserIdSetRoleRoute
  '/api/admin/users/$userId/unban': typeof ApiAdminUsersUserIdUnbanRoute
  '/api/admin/users/$userId/verify-email': typeof ApiAdminUsersUserIdVerifyEmailRoute
  '/api/user/connected-apps/$consentId/revoke': typeof ApiUserConnectedAppsConsentIdRevokeRoute
  '/api/user/passkeys/$passkeyId/delete': typeof ApiUserPasskeysPasskeyIdDeleteRoute
  '/api/user/sessions/$sessionId/revoke': typeof ApiUserSessionsSessionIdRevokeRoute
  '/api/admin/departments/$departmentId/members/$memberId/remove': typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRoute
  '/api/admin/departments/$departmentId/members/$memberId/role': typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRoute
  '/api/admin/departments/$departmentId/teams/$teamId/delete': typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRoute
  '/api/admin/departments/$departmentId/teams/$teamId/members': typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteWithChildren
  '/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove': typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/api/health': typeof ApiHealthRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/api/admin/branding': typeof ApiAdminBrandingRoute
  '/api/admin/clients': typeof ApiAdminClientsRouteWithChildren
  '/api/admin/departments': typeof ApiAdminDepartmentsRouteWithChildren
  '/api/admin/services': typeof ApiAdminServicesRouteWithChildren
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/services/$serviceId': typeof ApiServicesServiceIdRoute
  '/api/services/catalog': typeof ApiServicesCatalogRoute
  '/api/services/heartbeat': typeof ApiServicesHeartbeatRoute
  '/api/services/register': typeof ApiServicesRegisterRoute
  '/api/upload/avatar': typeof ApiUploadAvatarRoute
  '/api/user/connected-apps': typeof ApiUserConnectedAppsRouteWithChildren
  '/api/user/departments': typeof ApiUserDepartmentsRoute
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/api/user/passkeys': typeof ApiUserPasskeysRouteWithChildren
  '/api/user/password': typeof ApiUserPasswordRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/security-status': typeof ApiUserSecurityStatusRoute
  '/api/user/sessions': typeof ApiUserSessionsRouteWithChildren
  '/api/admin/clients/$clientId': typeof ApiAdminClientsClientIdRouteWithChildren
  '/api/admin/clients/register': typeof ApiAdminClientsRegisterRoute
  '/api/admin/departments/$departmentId': typeof ApiAdminDepartmentsDepartmentIdRouteWithChildren
  '/api/admin/departments/create': typeof ApiAdminDepartmentsCreateRoute
  '/api/admin/services/$serviceId': typeof ApiAdminServicesServiceIdRouteWithChildren
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRouteWithChildren
  '/api/admin/users/create': typeof ApiAdminUsersCreateRoute
  '/api/user/2fa/status': typeof ApiUser2faStatusRoute
  '/api/admin/clients/$clientId/actions': typeof ApiAdminClientsClientIdActionsRoute
  '/api/admin/departments/$departmentId/actions': typeof ApiAdminDepartmentsDepartmentIdActionsRoute
  '/api/admin/departments/$departmentId/delete': typeof ApiAdminDepartmentsDepartmentIdDeleteRoute
  '/api/admin/departments/$departmentId/members': typeof ApiAdminDepartmentsDepartmentIdMembersRouteWithChildren
  '/api/admin/departments/$departmentId/teams': typeof ApiAdminDepartmentsDepartmentIdTeamsRouteWithChildren
  '/api/admin/services/$serviceId/actions': typeof ApiAdminServicesServiceIdActionsRoute
  '/api/admin/services/$serviceId/delete': typeof ApiAdminServicesServiceIdDeleteRoute
  '/api/admin/services/$serviceId/toggle': typeof ApiAdminServicesServiceIdToggleRoute
  '/api/admin/users/$userId/actions': typeof ApiAdminUsersUserIdActionsRoute
  '/api/admin/users/$userId/ban': typeof ApiAdminUsersUserIdBanRoute
  '/api/admin/users/$userId/set-role': typeof ApiAdminUsersUserIdSetRoleRoute
  '/api/admin/users/$userId/unban': typeof ApiAdminUsersUserIdUnbanRoute
  '/api/admin/users/$userId/verify-email': typeof ApiAdminUsersUserIdVerifyEmailRoute
  '/api/user/connected-apps/$consentId/revoke': typeof ApiUserConnectedAppsConsentIdRevokeRoute
  '/api/user/passkeys/$passkeyId/delete': typeof ApiUserPasskeysPasskeyIdDeleteRoute
  '/api/user/sessions/$sessionId/revoke': typeof ApiUserSessionsSessionIdRevokeRoute
  '/api/admin/departments/$departmentId/members/$memberId/remove': typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRoute
  '/api/admin/departments/$departmentId/members/$memberId/role': typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRoute
  '/api/admin/departments/$departmentId/teams/$teamId/delete': typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRoute
  '/api/admin/departments/$departmentId/teams/$teamId/members': typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteWithChildren
  '/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove': typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/api/health': typeof ApiHealthRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/api/admin/branding': typeof ApiAdminBrandingRoute
  '/api/admin/clients': typeof ApiAdminClientsRouteWithChildren
  '/api/admin/departments': typeof ApiAdminDepartmentsRouteWithChildren
  '/api/admin/services': typeof ApiAdminServicesRouteWithChildren
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/services/$serviceId': typeof ApiServicesServiceIdRoute
  '/api/services/catalog': typeof ApiServicesCatalogRoute
  '/api/services/heartbeat': typeof ApiServicesHeartbeatRoute
  '/api/services/register': typeof ApiServicesRegisterRoute
  '/api/upload/avatar': typeof ApiUploadAvatarRoute
  '/api/user/connected-apps': typeof ApiUserConnectedAppsRouteWithChildren
  '/api/user/departments': typeof ApiUserDepartmentsRoute
  '/api/user/organizations': typeof ApiUserOrganizationsRoute
  '/api/user/passkeys': typeof ApiUserPasskeysRouteWithChildren
  '/api/user/password': typeof ApiUserPasswordRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/security-status': typeof ApiUserSecurityStatusRoute
  '/api/user/sessions': typeof ApiUserSessionsRouteWithChildren
  '/api/admin/clients/$clientId': typeof ApiAdminClientsClientIdRouteWithChildren
  '/api/admin/clients/register': typeof ApiAdminClientsRegisterRoute
  '/api/admin/departments/$departmentId': typeof ApiAdminDepartmentsDepartmentIdRouteWithChildren
  '/api/admin/departments/create': typeof ApiAdminDepartmentsCreateRoute
  '/api/admin/services/$serviceId': typeof ApiAdminServicesServiceIdRouteWithChildren
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRouteWithChildren
  '/api/admin/users/create': typeof ApiAdminUsersCreateRoute
  '/api/user/2fa/status': typeof ApiUser2faStatusRoute
  '/api/admin/clients/$clientId/actions': typeof ApiAdminClientsClientIdActionsRoute
  '/api/admin/departments/$departmentId/actions': typeof ApiAdminDepartmentsDepartmentIdActionsRoute
  '/api/admin/departments/$departmentId/delete': typeof ApiAdminDepartmentsDepartmentIdDeleteRoute
  '/api/admin/departments/$departmentId/members': typeof ApiAdminDepartmentsDepartmentIdMembersRouteWithChildren
  '/api/admin/departments/$departmentId/teams': typeof ApiAdminDepartmentsDepartmentIdTeamsRouteWithChildren
  '/api/admin/services/$serviceId/actions': typeof ApiAdminServicesServiceIdActionsRoute
  '/api/admin/services/$serviceId/delete': typeof ApiAdminServicesServiceIdDeleteRoute
  '/api/admin/services/$serviceId/toggle': typeof ApiAdminServicesServiceIdToggleRoute
  '/api/admin/users/$userId/actions': typeof ApiAdminUsersUserIdActionsRoute
  '/api/admin/users/$userId/ban': typeof ApiAdminUsersUserIdBanRoute
  '/api/admin/users/$userId/set-role': typeof ApiAdminUsersUserIdSetRoleRoute
  '/api/admin/users/$userId/unban': typeof ApiAdminUsersUserIdUnbanRoute
  '/api/admin/users/$userId/verify-email': typeof ApiAdminUsersUserIdVerifyEmailRoute
  '/api/user/connected-apps/$consentId/revoke': typeof ApiUserConnectedAppsConsentIdRevokeRoute
  '/api/user/passkeys/$passkeyId/delete': typeof ApiUserPasskeysPasskeyIdDeleteRoute
  '/api/user/sessions/$sessionId/revoke': typeof ApiUserSessionsSessionIdRevokeRoute
  '/api/admin/departments/$departmentId/members/$memberId/remove': typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRoute
  '/api/admin/departments/$departmentId/members/$memberId/role': typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRoute
  '/api/admin/departments/$departmentId/teams/$teamId/delete': typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRoute
  '/api/admin/departments/$departmentId/teams/$teamId/members': typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteWithChildren
  '/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove': typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/health'
    | '/oauth/consent'
    | '/api/admin/branding'
    | '/api/admin/clients'
    | '/api/admin/departments'
    | '/api/admin/services'
    | '/api/admin/settings'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/services/$serviceId'
    | '/api/services/catalog'
    | '/api/services/heartbeat'
    | '/api/services/register'
    | '/api/upload/avatar'
    | '/api/user/connected-apps'
    | '/api/user/departments'
    | '/api/user/organizations'
    | '/api/user/passkeys'
    | '/api/user/password'
    | '/api/user/profile'
    | '/api/user/security-status'
    | '/api/user/sessions'
    | '/api/admin/clients/$clientId'
    | '/api/admin/clients/register'
    | '/api/admin/departments/$departmentId'
    | '/api/admin/departments/create'
    | '/api/admin/services/$serviceId'
    | '/api/admin/users/$userId'
    | '/api/admin/users/create'
    | '/api/user/2fa/status'
    | '/api/admin/clients/$clientId/actions'
    | '/api/admin/departments/$departmentId/actions'
    | '/api/admin/departments/$departmentId/delete'
    | '/api/admin/departments/$departmentId/members'
    | '/api/admin/departments/$departmentId/teams'
    | '/api/admin/services/$serviceId/actions'
    | '/api/admin/services/$serviceId/delete'
    | '/api/admin/services/$serviceId/toggle'
    | '/api/admin/users/$userId/actions'
    | '/api/admin/users/$userId/ban'
    | '/api/admin/users/$userId/set-role'
    | '/api/admin/users/$userId/unban'
    | '/api/admin/users/$userId/verify-email'
    | '/api/user/connected-apps/$consentId/revoke'
    | '/api/user/passkeys/$passkeyId/delete'
    | '/api/user/sessions/$sessionId/revoke'
    | '/api/admin/departments/$departmentId/members/$memberId/remove'
    | '/api/admin/departments/$departmentId/members/$memberId/role'
    | '/api/admin/departments/$departmentId/teams/$teamId/delete'
    | '/api/admin/departments/$departmentId/teams/$teamId/members'
    | '/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/health'
    | '/oauth/consent'
    | '/api/admin/branding'
    | '/api/admin/clients'
    | '/api/admin/departments'
    | '/api/admin/services'
    | '/api/admin/settings'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/services/$serviceId'
    | '/api/services/catalog'
    | '/api/services/heartbeat'
    | '/api/services/register'
    | '/api/upload/avatar'
    | '/api/user/connected-apps'
    | '/api/user/departments'
    | '/api/user/organizations'
    | '/api/user/passkeys'
    | '/api/user/password'
    | '/api/user/profile'
    | '/api/user/security-status'
    | '/api/user/sessions'
    | '/api/admin/clients/$clientId'
    | '/api/admin/clients/register'
    | '/api/admin/departments/$departmentId'
    | '/api/admin/departments/create'
    | '/api/admin/services/$serviceId'
    | '/api/admin/users/$userId'
    | '/api/admin/users/create'
    | '/api/user/2fa/status'
    | '/api/admin/clients/$clientId/actions'
    | '/api/admin/departments/$departmentId/actions'
    | '/api/admin/departments/$departmentId/delete'
    | '/api/admin/departments/$departmentId/members'
    | '/api/admin/departments/$departmentId/teams'
    | '/api/admin/services/$serviceId/actions'
    | '/api/admin/services/$serviceId/delete'
    | '/api/admin/services/$serviceId/toggle'
    | '/api/admin/users/$userId/actions'
    | '/api/admin/users/$userId/ban'
    | '/api/admin/users/$userId/set-role'
    | '/api/admin/users/$userId/unban'
    | '/api/admin/users/$userId/verify-email'
    | '/api/user/connected-apps/$consentId/revoke'
    | '/api/user/passkeys/$passkeyId/delete'
    | '/api/user/sessions/$sessionId/revoke'
    | '/api/admin/departments/$departmentId/members/$memberId/remove'
    | '/api/admin/departments/$departmentId/members/$memberId/role'
    | '/api/admin/departments/$departmentId/teams/$teamId/delete'
    | '/api/admin/departments/$departmentId/teams/$teamId/members'
    | '/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/register'
    | '/_public/reset-password'
    | '/api/health'
    | '/oauth/consent'
    | '/api/admin/branding'
    | '/api/admin/clients'
    | '/api/admin/departments'
    | '/api/admin/services'
    | '/api/admin/settings'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/services/$serviceId'
    | '/api/services/catalog'
    | '/api/services/heartbeat'
    | '/api/services/register'
    | '/api/upload/avatar'
    | '/api/user/connected-apps'
    | '/api/user/departments'
    | '/api/user/organizations'
    | '/api/user/passkeys'
    | '/api/user/password'
    | '/api/user/profile'
    | '/api/user/security-status'
    | '/api/user/sessions'
    | '/api/admin/clients/$clientId'
    | '/api/admin/clients/register'
    | '/api/admin/departments/$departmentId'
    | '/api/admin/departments/create'
    | '/api/admin/services/$serviceId'
    | '/api/admin/users/$userId'
    | '/api/admin/users/create'
    | '/api/user/2fa/status'
    | '/api/admin/clients/$clientId/actions'
    | '/api/admin/departments/$departmentId/actions'
    | '/api/admin/departments/$departmentId/delete'
    | '/api/admin/departments/$departmentId/members'
    | '/api/admin/departments/$departmentId/teams'
    | '/api/admin/services/$serviceId/actions'
    | '/api/admin/services/$serviceId/delete'
    | '/api/admin/services/$serviceId/toggle'
    | '/api/admin/users/$userId/actions'
    | '/api/admin/users/$userId/ban'
    | '/api/admin/users/$userId/set-role'
    | '/api/admin/users/$userId/unban'
    | '/api/admin/users/$userId/verify-email'
    | '/api/user/connected-apps/$consentId/revoke'
    | '/api/user/passkeys/$passkeyId/delete'
    | '/api/user/sessions/$sessionId/revoke'
    | '/api/admin/departments/$departmentId/members/$memberId/remove'
    | '/api/admin/departments/$departmentId/members/$memberId/role'
    | '/api/admin/departments/$departmentId/teams/$teamId/delete'
    | '/api/admin/departments/$departmentId/teams/$teamId/members'
    | '/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAdminBrandingRoute: typeof ApiAdminBrandingRoute
  ApiAdminClientsRoute: typeof ApiAdminClientsRouteWithChildren
  ApiAdminDepartmentsRoute: typeof ApiAdminDepartmentsRouteWithChildren
  ApiAdminServicesRoute: typeof ApiAdminServicesRouteWithChildren
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiServicesServiceIdRoute: typeof ApiServicesServiceIdRoute
  ApiServicesCatalogRoute: typeof ApiServicesCatalogRoute
  ApiServicesHeartbeatRoute: typeof ApiServicesHeartbeatRoute
  ApiServicesRegisterRoute: typeof ApiServicesRegisterRoute
  ApiUploadAvatarRoute: typeof ApiUploadAvatarRoute
  ApiUserConnectedAppsRoute: typeof ApiUserConnectedAppsRouteWithChildren
  ApiUserDepartmentsRoute: typeof ApiUserDepartmentsRoute
  ApiUserOrganizationsRoute: typeof ApiUserOrganizationsRoute
  ApiUserPasskeysRoute: typeof ApiUserPasskeysRouteWithChildren
  ApiUserPasswordRoute: typeof ApiUserPasswordRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ApiUserSecurityStatusRoute: typeof ApiUserSecurityStatusRoute
  ApiUserSessionsRoute: typeof ApiUserSessionsRouteWithChildren
  ApiUser2faStatusRoute: typeof ApiUser2faStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/user/sessions': {
      id: '/api/user/sessions'
      path: '/api/user/sessions'
      fullPath: '/api/user/sessions'
      preLoaderRoute: typeof ApiUserSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/security-status': {
      id: '/api/user/security-status'
      path: '/api/user/security-status'
      fullPath: '/api/user/security-status'
      preLoaderRoute: typeof ApiUserSecurityStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile': {
      id: '/api/user/profile'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/password': {
      id: '/api/user/password'
      path: '/api/user/password'
      fullPath: '/api/user/password'
      preLoaderRoute: typeof ApiUserPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/passkeys': {
      id: '/api/user/passkeys'
      path: '/api/user/passkeys'
      fullPath: '/api/user/passkeys'
      preLoaderRoute: typeof ApiUserPasskeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/organizations': {
      id: '/api/user/organizations'
      path: '/api/user/organizations'
      fullPath: '/api/user/organizations'
      preLoaderRoute: typeof ApiUserOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/departments': {
      id: '/api/user/departments'
      path: '/api/user/departments'
      fullPath: '/api/user/departments'
      preLoaderRoute: typeof ApiUserDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/connected-apps': {
      id: '/api/user/connected-apps'
      path: '/api/user/connected-apps'
      fullPath: '/api/user/connected-apps'
      preLoaderRoute: typeof ApiUserConnectedAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/avatar': {
      id: '/api/upload/avatar'
      path: '/api/upload/avatar'
      fullPath: '/api/upload/avatar'
      preLoaderRoute: typeof ApiUploadAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/register': {
      id: '/api/services/register'
      path: '/api/services/register'
      fullPath: '/api/services/register'
      preLoaderRoute: typeof ApiServicesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/heartbeat': {
      id: '/api/services/heartbeat'
      path: '/api/services/heartbeat'
      fullPath: '/api/services/heartbeat'
      preLoaderRoute: typeof ApiServicesHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/catalog': {
      id: '/api/services/catalog'
      path: '/api/services/catalog'
      fullPath: '/api/services/catalog'
      preLoaderRoute: typeof ApiServicesCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/$serviceId': {
      id: '/api/services/$serviceId'
      path: '/api/services/$serviceId'
      fullPath: '/api/services/$serviceId'
      preLoaderRoute: typeof ApiServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/services': {
      id: '/api/admin/services'
      path: '/api/admin/services'
      fullPath: '/api/admin/services'
      preLoaderRoute: typeof ApiAdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/departments': {
      id: '/api/admin/departments'
      path: '/api/admin/departments'
      fullPath: '/api/admin/departments'
      preLoaderRoute: typeof ApiAdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/clients': {
      id: '/api/admin/clients'
      path: '/api/admin/clients'
      fullPath: '/api/admin/clients'
      preLoaderRoute: typeof ApiAdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/branding': {
      id: '/api/admin/branding'
      path: '/api/admin/branding'
      fullPath: '/api/admin/branding'
      preLoaderRoute: typeof ApiAdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/2fa/status': {
      id: '/api/user/2fa/status'
      path: '/api/user/2fa/status'
      fullPath: '/api/user/2fa/status'
      preLoaderRoute: typeof ApiUser2faStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/create': {
      id: '/api/admin/users/create'
      path: '/create'
      fullPath: '/api/admin/users/create'
      preLoaderRoute: typeof ApiAdminUsersCreateRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/services/$serviceId': {
      id: '/api/admin/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/api/admin/services/$serviceId'
      preLoaderRoute: typeof ApiAdminServicesServiceIdRouteImport
      parentRoute: typeof ApiAdminServicesRoute
    }
    '/api/admin/departments/create': {
      id: '/api/admin/departments/create'
      path: '/create'
      fullPath: '/api/admin/departments/create'
      preLoaderRoute: typeof ApiAdminDepartmentsCreateRouteImport
      parentRoute: typeof ApiAdminDepartmentsRoute
    }
    '/api/admin/departments/$departmentId': {
      id: '/api/admin/departments/$departmentId'
      path: '/$departmentId'
      fullPath: '/api/admin/departments/$departmentId'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdRouteImport
      parentRoute: typeof ApiAdminDepartmentsRoute
    }
    '/api/admin/clients/register': {
      id: '/api/admin/clients/register'
      path: '/register'
      fullPath: '/api/admin/clients/register'
      preLoaderRoute: typeof ApiAdminClientsRegisterRouteImport
      parentRoute: typeof ApiAdminClientsRoute
    }
    '/api/admin/clients/$clientId': {
      id: '/api/admin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/api/admin/clients/$clientId'
      preLoaderRoute: typeof ApiAdminClientsClientIdRouteImport
      parentRoute: typeof ApiAdminClientsRoute
    }
    '/api/user/sessions/$sessionId/revoke': {
      id: '/api/user/sessions/$sessionId/revoke'
      path: '/$sessionId/revoke'
      fullPath: '/api/user/sessions/$sessionId/revoke'
      preLoaderRoute: typeof ApiUserSessionsSessionIdRevokeRouteImport
      parentRoute: typeof ApiUserSessionsRoute
    }
    '/api/user/passkeys/$passkeyId/delete': {
      id: '/api/user/passkeys/$passkeyId/delete'
      path: '/$passkeyId/delete'
      fullPath: '/api/user/passkeys/$passkeyId/delete'
      preLoaderRoute: typeof ApiUserPasskeysPasskeyIdDeleteRouteImport
      parentRoute: typeof ApiUserPasskeysRoute
    }
    '/api/user/connected-apps/$consentId/revoke': {
      id: '/api/user/connected-apps/$consentId/revoke'
      path: '/$consentId/revoke'
      fullPath: '/api/user/connected-apps/$consentId/revoke'
      preLoaderRoute: typeof ApiUserConnectedAppsConsentIdRevokeRouteImport
      parentRoute: typeof ApiUserConnectedAppsRoute
    }
    '/api/admin/users/$userId/verify-email': {
      id: '/api/admin/users/$userId/verify-email'
      path: '/verify-email'
      fullPath: '/api/admin/users/$userId/verify-email'
      preLoaderRoute: typeof ApiAdminUsersUserIdVerifyEmailRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/users/$userId/unban': {
      id: '/api/admin/users/$userId/unban'
      path: '/unban'
      fullPath: '/api/admin/users/$userId/unban'
      preLoaderRoute: typeof ApiAdminUsersUserIdUnbanRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/users/$userId/set-role': {
      id: '/api/admin/users/$userId/set-role'
      path: '/set-role'
      fullPath: '/api/admin/users/$userId/set-role'
      preLoaderRoute: typeof ApiAdminUsersUserIdSetRoleRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/users/$userId/ban': {
      id: '/api/admin/users/$userId/ban'
      path: '/ban'
      fullPath: '/api/admin/users/$userId/ban'
      preLoaderRoute: typeof ApiAdminUsersUserIdBanRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/users/$userId/actions': {
      id: '/api/admin/users/$userId/actions'
      path: '/actions'
      fullPath: '/api/admin/users/$userId/actions'
      preLoaderRoute: typeof ApiAdminUsersUserIdActionsRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/services/$serviceId/toggle': {
      id: '/api/admin/services/$serviceId/toggle'
      path: '/toggle'
      fullPath: '/api/admin/services/$serviceId/toggle'
      preLoaderRoute: typeof ApiAdminServicesServiceIdToggleRouteImport
      parentRoute: typeof ApiAdminServicesServiceIdRoute
    }
    '/api/admin/services/$serviceId/delete': {
      id: '/api/admin/services/$serviceId/delete'
      path: '/delete'
      fullPath: '/api/admin/services/$serviceId/delete'
      preLoaderRoute: typeof ApiAdminServicesServiceIdDeleteRouteImport
      parentRoute: typeof ApiAdminServicesServiceIdRoute
    }
    '/api/admin/services/$serviceId/actions': {
      id: '/api/admin/services/$serviceId/actions'
      path: '/actions'
      fullPath: '/api/admin/services/$serviceId/actions'
      preLoaderRoute: typeof ApiAdminServicesServiceIdActionsRouteImport
      parentRoute: typeof ApiAdminServicesServiceIdRoute
    }
    '/api/admin/departments/$departmentId/teams': {
      id: '/api/admin/departments/$departmentId/teams'
      path: '/teams'
      fullPath: '/api/admin/departments/$departmentId/teams'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsRouteImport
      parentRoute: typeof ApiAdminDepartmentsDepartmentIdRoute
    }
    '/api/admin/departments/$departmentId/members': {
      id: '/api/admin/departments/$departmentId/members'
      path: '/members'
      fullPath: '/api/admin/departments/$departmentId/members'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdMembersRouteImport
      parentRoute: typeof ApiAdminDepartmentsDepartmentIdRoute
    }
    '/api/admin/departments/$departmentId/delete': {
      id: '/api/admin/departments/$departmentId/delete'
      path: '/delete'
      fullPath: '/api/admin/departments/$departmentId/delete'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdDeleteRouteImport
      parentRoute: typeof ApiAdminDepartmentsDepartmentIdRoute
    }
    '/api/admin/departments/$departmentId/actions': {
      id: '/api/admin/departments/$departmentId/actions'
      path: '/actions'
      fullPath: '/api/admin/departments/$departmentId/actions'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdActionsRouteImport
      parentRoute: typeof ApiAdminDepartmentsDepartmentIdRoute
    }
    '/api/admin/clients/$clientId/actions': {
      id: '/api/admin/clients/$clientId/actions'
      path: '/actions'
      fullPath: '/api/admin/clients/$clientId/actions'
      preLoaderRoute: typeof ApiAdminClientsClientIdActionsRouteImport
      parentRoute: typeof ApiAdminClientsClientIdRoute
    }
    '/api/admin/departments/$departmentId/teams/$teamId/members': {
      id: '/api/admin/departments/$departmentId/teams/$teamId/members'
      path: '/$teamId/members'
      fullPath: '/api/admin/departments/$departmentId/teams/$teamId/members'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteImport
      parentRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsRoute
    }
    '/api/admin/departments/$departmentId/teams/$teamId/delete': {
      id: '/api/admin/departments/$departmentId/teams/$teamId/delete'
      path: '/$teamId/delete'
      fullPath: '/api/admin/departments/$departmentId/teams/$teamId/delete'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRouteImport
      parentRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsRoute
    }
    '/api/admin/departments/$departmentId/members/$memberId/role': {
      id: '/api/admin/departments/$departmentId/members/$memberId/role'
      path: '/$memberId/role'
      fullPath: '/api/admin/departments/$departmentId/members/$memberId/role'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRouteImport
      parentRoute: typeof ApiAdminDepartmentsDepartmentIdMembersRoute
    }
    '/api/admin/departments/$departmentId/members/$memberId/remove': {
      id: '/api/admin/departments/$departmentId/members/$memberId/remove'
      path: '/$memberId/remove'
      fullPath: '/api/admin/departments/$departmentId/members/$memberId/remove'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRouteImport
      parentRoute: typeof ApiAdminDepartmentsDepartmentIdMembersRoute
    }
    '/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove': {
      id: '/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove'
      path: '/$teamMemberId/remove'
      fullPath: '/api/admin/departments/$departmentId/teams/$teamId/members/$teamMemberId/remove'
      preLoaderRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRouteImport
      parentRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRoute
    }
  }
}

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface ApiAdminClientsClientIdRouteChildren {
  ApiAdminClientsClientIdActionsRoute: typeof ApiAdminClientsClientIdActionsRoute
}

const ApiAdminClientsClientIdRouteChildren: ApiAdminClientsClientIdRouteChildren =
  {
    ApiAdminClientsClientIdActionsRoute: ApiAdminClientsClientIdActionsRoute,
  }

const ApiAdminClientsClientIdRouteWithChildren =
  ApiAdminClientsClientIdRoute._addFileChildren(
    ApiAdminClientsClientIdRouteChildren,
  )

interface ApiAdminClientsRouteChildren {
  ApiAdminClientsClientIdRoute: typeof ApiAdminClientsClientIdRouteWithChildren
  ApiAdminClientsRegisterRoute: typeof ApiAdminClientsRegisterRoute
}

const ApiAdminClientsRouteChildren: ApiAdminClientsRouteChildren = {
  ApiAdminClientsClientIdRoute: ApiAdminClientsClientIdRouteWithChildren,
  ApiAdminClientsRegisterRoute: ApiAdminClientsRegisterRoute,
}

const ApiAdminClientsRouteWithChildren = ApiAdminClientsRoute._addFileChildren(
  ApiAdminClientsRouteChildren,
)

interface ApiAdminDepartmentsDepartmentIdMembersRouteChildren {
  ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRoute: typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRoute
  ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRoute: typeof ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRoute
}

const ApiAdminDepartmentsDepartmentIdMembersRouteChildren: ApiAdminDepartmentsDepartmentIdMembersRouteChildren =
  {
    ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRoute:
      ApiAdminDepartmentsDepartmentIdMembersMemberIdRemoveRoute,
    ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRoute:
      ApiAdminDepartmentsDepartmentIdMembersMemberIdRoleRoute,
  }

const ApiAdminDepartmentsDepartmentIdMembersRouteWithChildren =
  ApiAdminDepartmentsDepartmentIdMembersRoute._addFileChildren(
    ApiAdminDepartmentsDepartmentIdMembersRouteChildren,
  )

interface ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteChildren {
  ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRoute
}

const ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteChildren: ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteChildren =
  {
    ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRoute:
      ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersTeamMemberIdRemoveRoute,
  }

const ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteWithChildren =
  ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRoute._addFileChildren(
    ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteChildren,
  )

interface ApiAdminDepartmentsDepartmentIdTeamsRouteChildren {
  ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRoute
  ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteWithChildren
}

const ApiAdminDepartmentsDepartmentIdTeamsRouteChildren: ApiAdminDepartmentsDepartmentIdTeamsRouteChildren =
  {
    ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRoute:
      ApiAdminDepartmentsDepartmentIdTeamsTeamIdDeleteRoute,
    ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRoute:
      ApiAdminDepartmentsDepartmentIdTeamsTeamIdMembersRouteWithChildren,
  }

const ApiAdminDepartmentsDepartmentIdTeamsRouteWithChildren =
  ApiAdminDepartmentsDepartmentIdTeamsRoute._addFileChildren(
    ApiAdminDepartmentsDepartmentIdTeamsRouteChildren,
  )

interface ApiAdminDepartmentsDepartmentIdRouteChildren {
  ApiAdminDepartmentsDepartmentIdActionsRoute: typeof ApiAdminDepartmentsDepartmentIdActionsRoute
  ApiAdminDepartmentsDepartmentIdDeleteRoute: typeof ApiAdminDepartmentsDepartmentIdDeleteRoute
  ApiAdminDepartmentsDepartmentIdMembersRoute: typeof ApiAdminDepartmentsDepartmentIdMembersRouteWithChildren
  ApiAdminDepartmentsDepartmentIdTeamsRoute: typeof ApiAdminDepartmentsDepartmentIdTeamsRouteWithChildren
}

const ApiAdminDepartmentsDepartmentIdRouteChildren: ApiAdminDepartmentsDepartmentIdRouteChildren =
  {
    ApiAdminDepartmentsDepartmentIdActionsRoute:
      ApiAdminDepartmentsDepartmentIdActionsRoute,
    ApiAdminDepartmentsDepartmentIdDeleteRoute:
      ApiAdminDepartmentsDepartmentIdDeleteRoute,
    ApiAdminDepartmentsDepartmentIdMembersRoute:
      ApiAdminDepartmentsDepartmentIdMembersRouteWithChildren,
    ApiAdminDepartmentsDepartmentIdTeamsRoute:
      ApiAdminDepartmentsDepartmentIdTeamsRouteWithChildren,
  }

const ApiAdminDepartmentsDepartmentIdRouteWithChildren =
  ApiAdminDepartmentsDepartmentIdRoute._addFileChildren(
    ApiAdminDepartmentsDepartmentIdRouteChildren,
  )

interface ApiAdminDepartmentsRouteChildren {
  ApiAdminDepartmentsDepartmentIdRoute: typeof ApiAdminDepartmentsDepartmentIdRouteWithChildren
  ApiAdminDepartmentsCreateRoute: typeof ApiAdminDepartmentsCreateRoute
}

const ApiAdminDepartmentsRouteChildren: ApiAdminDepartmentsRouteChildren = {
  ApiAdminDepartmentsDepartmentIdRoute:
    ApiAdminDepartmentsDepartmentIdRouteWithChildren,
  ApiAdminDepartmentsCreateRoute: ApiAdminDepartmentsCreateRoute,
}

const ApiAdminDepartmentsRouteWithChildren =
  ApiAdminDepartmentsRoute._addFileChildren(ApiAdminDepartmentsRouteChildren)

interface ApiAdminServicesServiceIdRouteChildren {
  ApiAdminServicesServiceIdActionsRoute: typeof ApiAdminServicesServiceIdActionsRoute
  ApiAdminServicesServiceIdDeleteRoute: typeof ApiAdminServicesServiceIdDeleteRoute
  ApiAdminServicesServiceIdToggleRoute: typeof ApiAdminServicesServiceIdToggleRoute
}

const ApiAdminServicesServiceIdRouteChildren: ApiAdminServicesServiceIdRouteChildren =
  {
    ApiAdminServicesServiceIdActionsRoute:
      ApiAdminServicesServiceIdActionsRoute,
    ApiAdminServicesServiceIdDeleteRoute: ApiAdminServicesServiceIdDeleteRoute,
    ApiAdminServicesServiceIdToggleRoute: ApiAdminServicesServiceIdToggleRoute,
  }

const ApiAdminServicesServiceIdRouteWithChildren =
  ApiAdminServicesServiceIdRoute._addFileChildren(
    ApiAdminServicesServiceIdRouteChildren,
  )

interface ApiAdminServicesRouteChildren {
  ApiAdminServicesServiceIdRoute: typeof ApiAdminServicesServiceIdRouteWithChildren
}

const ApiAdminServicesRouteChildren: ApiAdminServicesRouteChildren = {
  ApiAdminServicesServiceIdRoute: ApiAdminServicesServiceIdRouteWithChildren,
}

const ApiAdminServicesRouteWithChildren =
  ApiAdminServicesRoute._addFileChildren(ApiAdminServicesRouteChildren)

interface ApiAdminUsersUserIdRouteChildren {
  ApiAdminUsersUserIdActionsRoute: typeof ApiAdminUsersUserIdActionsRoute
  ApiAdminUsersUserIdBanRoute: typeof ApiAdminUsersUserIdBanRoute
  ApiAdminUsersUserIdSetRoleRoute: typeof ApiAdminUsersUserIdSetRoleRoute
  ApiAdminUsersUserIdUnbanRoute: typeof ApiAdminUsersUserIdUnbanRoute
  ApiAdminUsersUserIdVerifyEmailRoute: typeof ApiAdminUsersUserIdVerifyEmailRoute
}

const ApiAdminUsersUserIdRouteChildren: ApiAdminUsersUserIdRouteChildren = {
  ApiAdminUsersUserIdActionsRoute: ApiAdminUsersUserIdActionsRoute,
  ApiAdminUsersUserIdBanRoute: ApiAdminUsersUserIdBanRoute,
  ApiAdminUsersUserIdSetRoleRoute: ApiAdminUsersUserIdSetRoleRoute,
  ApiAdminUsersUserIdUnbanRoute: ApiAdminUsersUserIdUnbanRoute,
  ApiAdminUsersUserIdVerifyEmailRoute: ApiAdminUsersUserIdVerifyEmailRoute,
}

const ApiAdminUsersUserIdRouteWithChildren =
  ApiAdminUsersUserIdRoute._addFileChildren(ApiAdminUsersUserIdRouteChildren)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRouteWithChildren
  ApiAdminUsersCreateRoute: typeof ApiAdminUsersCreateRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRouteWithChildren,
  ApiAdminUsersCreateRoute: ApiAdminUsersCreateRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiUserConnectedAppsRouteChildren {
  ApiUserConnectedAppsConsentIdRevokeRoute: typeof ApiUserConnectedAppsConsentIdRevokeRoute
}

const ApiUserConnectedAppsRouteChildren: ApiUserConnectedAppsRouteChildren = {
  ApiUserConnectedAppsConsentIdRevokeRoute:
    ApiUserConnectedAppsConsentIdRevokeRoute,
}

const ApiUserConnectedAppsRouteWithChildren =
  ApiUserConnectedAppsRoute._addFileChildren(ApiUserConnectedAppsRouteChildren)

interface ApiUserPasskeysRouteChildren {
  ApiUserPasskeysPasskeyIdDeleteRoute: typeof ApiUserPasskeysPasskeyIdDeleteRoute
}

const ApiUserPasskeysRouteChildren: ApiUserPasskeysRouteChildren = {
  ApiUserPasskeysPasskeyIdDeleteRoute: ApiUserPasskeysPasskeyIdDeleteRoute,
}

const ApiUserPasskeysRouteWithChildren = ApiUserPasskeysRoute._addFileChildren(
  ApiUserPasskeysRouteChildren,
)

interface ApiUserSessionsRouteChildren {
  ApiUserSessionsSessionIdRevokeRoute: typeof ApiUserSessionsSessionIdRevokeRoute
}

const ApiUserSessionsRouteChildren: ApiUserSessionsRouteChildren = {
  ApiUserSessionsSessionIdRevokeRoute: ApiUserSessionsSessionIdRevokeRoute,
}

const ApiUserSessionsRouteWithChildren = ApiUserSessionsRoute._addFileChildren(
  ApiUserSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAdminBrandingRoute: ApiAdminBrandingRoute,
  ApiAdminClientsRoute: ApiAdminClientsRouteWithChildren,
  ApiAdminDepartmentsRoute: ApiAdminDepartmentsRouteWithChildren,
  ApiAdminServicesRoute: ApiAdminServicesRouteWithChildren,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiServicesServiceIdRoute: ApiServicesServiceIdRoute,
  ApiServicesCatalogRoute: ApiServicesCatalogRoute,
  ApiServicesHeartbeatRoute: ApiServicesHeartbeatRoute,
  ApiServicesRegisterRoute: ApiServicesRegisterRoute,
  ApiUploadAvatarRoute: ApiUploadAvatarRoute,
  ApiUserConnectedAppsRoute: ApiUserConnectedAppsRouteWithChildren,
  ApiUserDepartmentsRoute: ApiUserDepartmentsRoute,
  ApiUserOrganizationsRoute: ApiUserOrganizationsRoute,
  ApiUserPasskeysRoute: ApiUserPasskeysRouteWithChildren,
  ApiUserPasswordRoute: ApiUserPasswordRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiUserSecurityStatusRoute: ApiUserSecurityStatusRoute,
  ApiUserSessionsRoute: ApiUserSessionsRouteWithChildren,
  ApiUser2faStatusRoute: ApiUser2faStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
